add feature evaluation
saranicoly/ess-project pull request #22
Opened 2024-02-17 16:25 UTC by arthurzx22aa

criei a api da feature de avaliação

2024-02-17 16:36 UTC, yasmws commented on backend/src/main.py
Ajeitar. Coloque somente as funções criadas, coloque elas depois do código já existente.

2024-02-17 16:37 UTC, yasmws commented on backend/src/users.py
> -import firebase_config
Por que retirou?

2024-02-17 16:38 UTC, yasmws requested changes
main.py e users.py com conflito.

2024-02-17 20:10 UTC, yasmws commented on backend/src/main.py
O create_reservations sumiu, tenta colocar ele de volta.

2024-02-17 20:41 UTC, yasmws approved these changes
Ok!

2024-02-18 01:02 UTC, saranicoly requested changes

2024-02-18 01:02 UTC, saranicoly commented on backend/src/conftest.py
seria bom colocar esse arquivo numa outra pasta. Em vez de ser no src, na pasta tests.

2024-02-18 01:02 UTC, saranicoly commented on backend/src/pytest.init
colocar dentro da pasta tests

2024-02-18 01:02 UTC, saranicoly commented on backend/src/test/features/evaluate.feature
remover esse arquivo do PR, já que nao tem nada.

2024-02-18 01:02 UTC, saranicoly commented on backend/src/test/step_definitions/step.py
remover esse arquivo do PR, já que nao tem nada.

2024-02-18 01:06 UTC, arthurzx22aa commented on README.md
não me lembro de ter feito isso deter sido no merge

2024-02-18 01:06 UTC, arthurzx22aa commented on backend/src/conftest.py
eu segui o que tem na monitoria não tenho certeza se isso está certo ou não

2024-02-18 01:08 UTC, arthurzx22aa commented on backend/src/test/features/evaluate.feature
eu deixei ele porque vou  adicionar os cenários de serviço nele e quando eu deixava sem arquivo a pasta feature não era enviada no push

2024-02-18 20:50 UTC, closed without merging